class NotAuthenticatedException(Exception):
    ...

class InvalidPasswordException(Exception):
    ...

class UserAlreadyRegisteredException(Exception):
    ...

class UserNotFoundException(Exception):
    ...

class MFAException(Exception):
    ...